language: php

php:
  - 5.3
  - 5.4
  - 5.5
  # Not support xdebug_get_headers()
  #- hhvm

script:
  - cd protected/
  - composer install
  - php yiic migrate --interactive=0
  - cd tests/
  - phpunit
