language: php

php:
  - 5.3
  - 5.4
  - 5.5
  # Not support xdebug_get_headers()
  #- hhvm

script:
  - composer install -d protected/
  - protected/yiic migrate --interactive=0
  - phpunit -c protected/tests/phpunit.xml
